#pragma once
#ifndef _JOYSTICKMAPPING_
#define _JOYSTICKMAPPING_

#define JOY_BUTTON_UP 13
#define JOY_BUTTON_DOWN 12
#define JOY_BUTTON_RIGHT 10
#define JOY_BUTTON_LEFT 11
#define JOY_BUTTON_A 0
#define JOY_BUTTON_B 1

#define JOY_BUTTON_START 9

#endif // !_JOYSTICKMAPPING_
